name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: First
        env:
          SECRET: ${{ secrets.SECRET_1 }}
        run: chmod +x ./echo.sh; ./echo.sh "$SECRET"
      - name: Release
        if: github.event_name == 'push'
        env:
          SECRET: ${{ secrets.SECRET_2 }}
        run: chmod +x ./echo.sh; ./echo.sh "$SECRET"
